GET http://localhost:3000/todos/?status=TO%20DO 

GET http://localhost:3000/todos/?priority=HIGH

GET http://localhost:3000/todos/?category=HOME


GET http://localhost:3000/todos/?search_q=Buy


GET http://localhost:3000/todos/?priority=IN%20PROGRESS&status=TO%20DO

GET http://localhost:3000/todos/?status=DONE&category=WORK 

GET http://localhost:3000/todos/?category=LEARNING&priority=HIGH 

PUT http://localhost:3000/todos/6/

{
    "status":"HOME"
}




